name: venton_pro
description: VENTON PRO - Plataforma publicitaria para negocios en Colombia, España, Venezuela y USA.
publish_to: 'none'
version: 2.1.8+6

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  video_player: ^2.9.2
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  share_plus: ^10.1.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
