name: venton_pro
description: VENTON PRO - Plataforma móvil para emprendedores y consumidores en Colombia, USA y Venezuela.
publish_to: 'none'
version: 2.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
